version: '3'

services:
  node-server:
    build: ~/Projects/SOA/node-server
    ports:
    - "3005:3005"
    command: npm start
    volumes:
    - ~/Projects/SOA/node-server:/app
    networks:
    - docker_mainflux-base-net
  react-client:
    build:
      context: ~/Projects/SOA/react-client
      args:
        - NODE_ENV=development
    ports:
      - "1233:1233"
      - "1234:1234"
      - "3010:3001"
      - "38771:38771"
    command: npm start
    volumes:
      - ~/Projects/SOA/react-client:/app
    environment:
      - NODE_ENV=development
    networks:
      - docker_mainflux-base-net
    depends_on:
      - node-server
